# Generated by Django 3.0.7 on 2020-06-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentWeb', '0002_auto_20200626_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourses',
            unique_together={('student', 'course')},
        ),
    ]
